 alias dst=/root/dstrad
 alias traw=/root/trawd
 alias proxy_on='export http_proxy=http://host.docker.internal:1087;export https_proxy=$http_proxy'
 alias proxy_off='unset http_proxy;unset https_proxy'
 alias get_go_dep='go get github.com/golang/dep/cmd/dep'
 alias get_go_vg='go get github.com/GetStream/vg'

 command -v vg >/dev/null 2>&1 && eval "$(vg eval --shell bash)"
